spring.application.name=cash-flow-recorder

# Server-Config.
server.port=8080
server.servlet.context-path=/api

# Spring JPA
spring.jpa.database=POSTGRESQL
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update --> Daten behalten, aber bei Aenderungen am Modell, Relationen updaten
# Create new tables by starting Spring:
# spring.jpa.hibernate.ddl-auto=create --> immer initial befuellen
spring.jpa.hibernate.ddl-auto=create
#spring.jpa.hibernate.ddl-auto=none --> produktiv
spring.jpa.hibernate.enable_lazy_load_no_trans=true
spring.jpa.hibernate.naming-strategy=org.hibernate.cfg.ImprovedNamingStrategy

# PostgreSQL-DB
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://192.168.178.32:5532/cashflow
spring.datasource.url=jdbc:postgresql://localhost:5532/cashflow
spring.datasource.username=test
spring.datasource.password=test

# Multipart-Config.
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB

# Root-Level-Logging
logging.level.root=INFO
logging.file.name=logs/application.log
logging.file.max-size=10MB

# Tesseract OCR Configuration
tesseract.language=deu
tesseract.datapath=/usr/share/tesseract-ocr/5/tessdata
#tesseract.datapath=C:\\Program Files\\Tesseract-OCR\\tessdata
#tesseract.datapath=/usr/share/tesseract/tessdata/
tesseract.userDefineDpi=300
#tesseract.charWhiteList=ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-,.?

# String Match Pattern
pattern.sumMatchPattern.regexp=\\b(summe|\
  gesamt|\
  total|\
  kartenzahlung|\
  karte|\
  bruttoumsatz|\
  girocard|\
  gesamtbetrag|\
  auftragswert|\
  visa|\
  betrag|\
  brutto|\
  ec-cash|\
  ec cash|\
  zahlen)\\b.*\\b(\\d+[,.]\\d{2}).*

# Dictionary
#dictionary.file=/lib/de_DE.dic
dictionary.file=/lib/hunspell/alle_woerter.txt